<?php
$sess = isset($_GET['sess']) ? $_GET['sess'] : "";
echo $sess;
//var_dump($datas);
?>
<html>
    <head>
        <script type="text/javascript" src="/datepicker/js/bootstrap-datepicker.js"></script>
        <link href="/datepicker/css/datepicker.css" rel="stylesheet" type="text/css">
        <script type="text/javascript" src="http://platform.linkedin.com/in.js">
            api_key: jfzqnuuz7z00
            onLoad: onLinkedInLoad
            scope: r_fullprofile,r_basicprofile
        </script>

    <input type="hidden">

    <!-- NOTE: be sure to set onLoad: onLinkedInLoad -->
    <script type="text/javascript">
        function onLinkedInLoad() {
            
            IN.Event.on(IN, "auth", function() {onLinkedInLogin();});
            IN.Event.on(IN, "logout", function() {onLinkedInLogout();});
 
            //              $('a[id*=li_ui_li_gen_]').css({marginBottom:'20px'}).html('<img src="./images/ln.jpg" height="31" width="200" border="0" />'); 
        }
        setLoginBadge(true);
        function onLinkedInLogout() {
            setLoginBadge(false);
 
        }

        function onLinkedInLogin() {
            // we pass field selectors as a single parameter (array of strings)
            IN.API.Profile("me")
            .fields(["id", "firstName", "lastName","dateOfBirth","positions:(title,summary,startDate,endDate,company:(name))",
                "educations:(schoolName,fieldOfStudy,startDate,endDate,degree,activities,notes)","skills","pictureUrl",
                "interests"])
            .result(function(result) {
                setLoginBadge(result.values[0]);
            })
            .error(function(err) {
                alert(err);
            });
        }
        function logOut()
        {	
            IN.User.logout();
            document.getElementById('loginbadge').style.display='none';
        }
         
        function setLoginBadge(profile) {
            pos_title = new Array();
            pos_company = new Array();
            pos_date = new Array();
            pos_summary = new Array();
            edu_schoolName = new Array();
            edu_fieldOfStudy = new Array();
            edu_date = new Array();
            edu_degree = new Array();
            edu_activities = new Array();
            edu_notes = new Array();
            skill = new Array();
            id = profile.id;
            last_name = profile.lastName;
            first_name = profile.firstName;
            j=0;
            k=0;
            l=0;
            if(profile.positions !=null){
                j=profile.positions._total;
            }
            if(profile.educations != null){
                k=profile.educations._total;
            }
            if(profile.skills != null){
                l=profile.skills._total;
            }
                          
            if (!profile) {
                profHTML = "<form method='post' action='insert'>\n\
                            <table>\n\
                            <tr>\n\
                            <td colspan='2'><img src='http://static02.linkedin.com/scds/common/u/img/icon/icon_no_photo_80x80.png'>\n\
                                <input type='text' id='sess' name='sess' value='<?php echo $sess; ?>'></td>\n\
                            </tr>\n\
                            <tr>\n\
                                <td width='100px'>Upload Profile</td> <td>: <input type='file' id='pic_url' name='pic_url'></td>\n\
                            </tr>\n\
                            <input type='hidden' id='id' name='id'>\n\
                            <tr>\n\
                                <td width='100px'>First Name</td> <td>: <input type='text' id='first_name' name='first_name'></td>\n\
                            </tr>\n\
                            <tr>\n\
                                <td width='100px'>Last Name</td> <td>: <input type='text' id='last_name' name='last_name'></td>\n\
                            </tr>\n\
                            <tr>\n\
                            <td colspan='2'><hr width='600px'></td>\n\
                            </tr>\n\
                            <tr>\n\
                            <td colspan='2'><h2>EXPERIENCES</h2></td>\n\
                            </tr>\n\
                            <tr>\n\
                                <td width='100px'>Position</td> <td>: <input type='text' id='pos_title' name='pos_title'></td>\n\
                            </tr>\n\
                            <tr>\n\
                                <td width='100px'>Company</td> <td>: <input type='text' id='pos_company' name='pos_company'></td>\n\
                            </tr>\n\
                            <tr>\n\
                                <td width='100px'>Date</td> <td>: <input type='date' id='pos_date' name='pos_date'></td>\n\
                            </tr>\n\
                            <tr>\n\
                                <td width='100px'>Summary</td> <td>: <textarea width='400px' height='200px' id='pos_summary' name ='pos_summary'></textarea></td>\n\
                            </tr>\n\
                            <tr>\n\
                            <td colspan='2'><hr width='600px'></td>\n\
                            </tr>\n\
                            <tr>\n\
                            <td colspan='2'><h2>EDUCATION</h2></td>\n\
                            </tr>\n\
                            <tr>\n\
                                <td width='100px'>School Name</td> <td>: <input type='text' id='edu_schoolName' name='edu_schoolName'></td>\n\
                            </tr>\n\
                            <tr>\n\
                                <td width='100px'>Field Of Study</td> <td>: <input type='text' id='edu_fieldOfStudy' name='edu_fieldOfStudy'></td>\n\
                            </tr>\n\
                            <tr>\n\
                                <td width='100px'>Date</td> <td>: <input type='date' id='edu_date' name='edu_date'></td>\n\
                            </tr>\n\
                            <tr>\n\
                                <td width='100px'>Degree</td> <td>: <input type='text' id='edu_degree' name='edu_degree'></td>\n\
                            </tr>\n\
                            <tr>\n\
                                <td width='100px'>Activities</td> <td>: <textarea width='400px' height='200px' id='edu_activities' name='edu_activities'></textarea></td>\n\
                            </tr>\n\
                            <tr>\n\
                                <td width='100px'>Notes</td> <td>: <textarea width='400px' height='200px' id='edu_note' name='edu_note'></textarea></td>\n\
                            </tr>\n\
                            <tr>\n\
                            <td colspan='2'><hr width='600px'></td>\n\
                            </tr>\n\
                            <tr>\n\
                            <td colspan='2'><h2>ADDITIONAL INFORMATION</h2></td>\n\
                            </tr>\n\
                            <tr>\n\
                                <td width='100px'>Interest</td> <td>: <textarea width='400px' height='200px' id='interest' name='interest'></textarea></td>\n\
                            </tr>\n\
                            <tr>\n\
                                <td width='100px'>Date Of Birth</td> <td>: <input type='date' id='dateOfBirth' name='dateOfBirth'></td>\n\
                            </tr>\n\
                            <tr>\n\
                                <td width='100px'><input type='submit' value='SUBMIT' class='btn'></td>\n\
                            </tr>\n\
                        </table>\n\
                    </form>";
                document.getElementById('loginbadge').style.display='block';
                document.getElementById('loginbadge').innerHTML=profHTML;
           }else {
                if(profile.dateOfBirth != null){
                    dateOfBirth = profile.dateOfBirth.day+"-"+profile.dateOfBirth.month+"-"+profile.dateOfBirth.year;
                }else{
                    dateOfBirth = '';
                }
                if(profile.interests != null){
                    interest = profile.interests;
                }else{
                    interest = "";
                }
                for(var i=0;i<l;i++){
                    skill[i] = profile.skills.values[i].skill.name;
                }  
                //experiences
                for (var i=0;i<j;i++){
                    pos_title[i] = profile.positions.values[i].title;
                    pos_company[i] = profile.positions.values[i].company.name;
                    //alert(profile.positions.values[0].endDate);
                    if((profile.positions.values[i].startDate == null)&&(profile.positions.values[i].endDate != null)){
                        pos_date[i]="0/0/00-"+"0/"+profile.positions.values[i].endDate.month +"/"+profile.positions.values[i].endDate.year;
                    }else if((profile.positions.values[i].startDate != null)&&(profile.positions.values[i].endDate == null)){
                        pos_date[i]="0/"+profile.positions.values[i].startDate.month +"/"+ profile.positions.values[i].startDate.year+"-0/0/00";
                    }else if((profile.positions.values[i].startDate != null)&&(profile.positions.values[i].endDate != null)){
                        pos_date[i]="0/"+profile.positions.values[i].startDate.month +"/"+ profile.positions.values[i].startDate.year+"-0/"+profile.positions.values[i].endDate.month +"/"+profile.positions.values[i].endDate.year;
                    }else{
                        pos_date[i]="<i>Unknow</i>";
                    }
                    pos_summary[i] = profile.positions.values[i].summary;

                }
                //education
                for(var i=0;i<k;i++){
                    edu_schoolName[i] = profile.educations.values[i].schoolName;
                    edu_fieldOfStudy[i] =profile.educations.values[i].fieldOfStudy;

                    if((profile.educations.values[i].startDate == null)&&(profile.educations.values[i].endDate != null)){
                        edu_date[i] ="0/0/00-"+profile.educations.values[i].endDate.year;
                    }else if((profile.educations.values[i].endDate == null)&&(profile.educations.values[i].startDate != null)){
                        edu_date[i] =profile.educations.values[i].endDate.year+"-0/0/00";
                    }else if ((profile.educations.values[i].startDate != null)&&(profile.educations.values[i].endDate != null)){
                        edu_date[i] =profile.educations.values[i].startDate.year+"-"+profile.educations.values[i].endDate.year;
                    }else{
                        edu_date[i]="<i>Unknow</i>"
                    }

                    edu_degree[i] =profile.educations.values[i].degree;
                    edu_activities[i] = profile.educations.values[i].activities;
                    edu_notes[i] =profile.educations.values[i].notes;
                }
                //additional info


                var pictureUrl = profile.pictureUrl || "http://static02.linkedin.com/scds/common/u/img/icon/icon_no_photo_80x80.png";

//                profHTML = "<p><button onClick=\"logOut();\">Logout</button><br><br>";
                ////                                profHTML = profHTML +"<form onsubmit='"+logOut()+"'>;
                //                                profHTML = profHTML +"<a href=\"" + profile.publicProfileUrl + "\">";
                //                                profHTML = profHTML + "<img src=\"" + pictureUrl + "\"></a><br>";
                ////                                profHTML = profHTML + first_name + " " + last_name;
                //                                profHTML = profHTML + "<hr width=600px align='left'>";
                //                                profHTML = profHTML + "<h2>EXPERIENCES</h2>";
                //                                for(var i=0;i<j;i++){
                //      
                //                                    profHTML = profHTML + "<b>"+pos_title[i]+"</b><br>";
                //                                    profHTML = profHTML + pos_company[i]+"<br>";
                //                                    profHTML = profHTML + "DATE : "+pos_date[i]+"<br>";
                //                                    profHTML = profHTML + "SUMMARY : <div style='width:550px; padding-left:40px;'>"+pos_summary[i]+"</div>";
                //                                    profHTML = profHTML +"<br>";
                //                                }
                //                                profHTML = profHTML + "<hr width=600px align='left'>";
                //                                profHTML = profHTML + "<h2>EDUCATION</h2>";
                //                                for(var i=0;i<k;i++){
                //                                    profHTML = profHTML + "<b>"+edu_schoolName[i]+"</b><br>";
                //                                    profHTML = profHTML + "FIELD OF STUDY : "+edu_fieldOfStudy[i]+"<br>";
                //                                    profHTML = profHTML + "DATE : "+edu_date[i]+"<br>";
                //                                    profHTML = profHTML + "DEGREE : "+edu_degree[i]+"<br>";
                //                                    profHTML = profHTML + "ACTIVITIES : <div style='width:550px; padding-left:40px;'>"+edu_activities[i]+"</div>";
                //                                    profHTML = profHTML + "NOTES : <div style='width:550px; padding-left:40px;'>"+edu_notes[i]+"</div>";
                //                                    profHTML = profHTML +"<br>";
                //                                }
                //                                profHTML = profHTML + "<hr width=600px align='left'>";
                //                                profHTML = profHTML + "<h2>ADDITIONAL INFORMATION</h2>";
                //                                profHTML = profHTML + "INTEREST : "+interest+"<br>";
                //                                profHTML = profHTML + "DATE OF BIRTH : "+dateOfBirth+"<br><br></p>";
                //                                profHTML = "";
                profHTML = "<form method='post' action="+'insert'+">";
                profHTML = profHTML + "<input type='hidden' id='pic_url' name='pic_url' value='"+pictureUrl+"'><br>";
                profHTML =profHTML + "<input type='hidden' id='id' name='id' value='"+id+"'><br>";
                profHTML = profHTML + "<input type='hidden' id='j' name='j' value='"+j+"'><br>";
                profHTML = profHTML + "<input type='hidden' id='k' name='k' value='"+k+"'><br>";
                profHTML = profHTML + "<input type='hidden' id='div_id' value='loginbadge'>";
                profHTML = profHTML + "<table>";
                profHTML = profHTML + "<tr>";
                profHTML = profHTML + "<td width='100px' colspan='2'><img src='"+pictureUrl+"'></td>";
                profHTML = profHTML + "</tr><tr>";
                profHTML =profHTML + "<td width='100px'>First Name</td><td>: <input type='text' id='first_name' name='first_name' value='"+first_name+"'></td>";
                profHTML = profHTML + "</tr><tr>";
                profHTML =profHTML + "<td width='100px'>Last Name</td><td> : <input type='text' id='last_name' name='last_name' value='"+last_name+"'></td>";
                profHTML = profHTML + "</tr><tr>";
                profHTML = profHTML + "<td width='100px'>Job Category</td><td> :";
                profHTML = profHTML + "<select id='jobs_cate' name='jobs_cate'>";

                <?php foreach ($data as $row): ?>
                        profHTML = profHTML + "<option value='<?php echo $row->cat_id; ?>'><?php echo $row->cat_name; ?></option>";
                <?php endforeach;
                ?>
                profHTML = profHTML +"</select></td>";
                profHTML = profHTML + "<td colspan='2'><hr width=600px align='left'></td>";
                profHTML = profHTML + "</tr><tr>";
                profHTML = profHTML + "<td colspan='2'><h2>EXPERIENCES</h2></td>";
                profHTML = profHTML + "</tr>";

                for(var i=0;i<j;i++){
                    profHTML = profHTML +"<tr>";
                    profHTML =profHTML + "<td width='100px'>Position</td><td> : <input type='text' id='pos_title["+i+"]' name='pos_title' value='"+pos_title[i]+"'>";
                    profHTML = profHTML +"</td>";
                    profHTML = profHTML + "</tr><tr>";
                    profHTML =profHTML + "<td width='100px'>Company</td><td> : <input type='text' id='pos_company["+i+"]' name='pos_company' value='"+pos_company[i]+"'></td>";
                    profHTML = profHTML + "</tr><tr>";
                    profHTML =profHTML + "<td width='100px'>Date</td><td> : <input type='text' id='pos_date["+i+"]' name='pos_date' value='"+pos_date[i]+"'></td>";
                    profHTML = profHTML + "</tr><tr>";
                    profHTML =profHTML + "<td width='100px'>Summary</td><td> :<textarea id='pos_summary["+i+"]' name='pos_summary'>"+pos_summary[i]+"</textarea></td>";
                    profHTML =profHTML +"</tr><tr><td colspan='2'><hr width=200px align='left' style='margin-left:50px;'></td></tr>";
                }
                profHTML = profHTML +"<tr>";
                profHTML = profHTML + "<td colspan='2'><hr width=600px align='left'></td>";
                profHTML = profHTML + "</tr><tr>";
                profHTML = profHTML + "<td colspan='2'><h2>EDUCATION</h2></td>";
                profHTML = profHTML + "</tr>";
                for(var i=0;i<k;i++){
                    profHTML = profHTML +"<tr>";
                    profHTML =profHTML + "<td width='100px'>School</td><td> : <input type='text' id='edu_schoolName["+i+"]' name='edu_schoolName' value='"+edu_schoolName[i]+"'></td>";
                    profHTML = profHTML + "</tr><tr>";
                    profHTML =profHTML + "<td width='100px'>Field</td><td> : <input type='text' id='edu_fieldOfStudy["+i+"]' name='edu_fieldOfStudy' value='"+edu_fieldOfStudy[i]+"'></td>";
                    profHTML = profHTML + "</tr><tr>";
                    profHTML =profHTML + "<td width='100px'>Date</td><td> : <input type='text' id='edu_date["+i+"]' name='edu_date' value='"+edu_date[i]+"'></td>";
                    profHTML = profHTML + "</tr><tr>";
                    profHTML =profHTML + "<td width='100px'>Degree</td><td> : <input type='text' id='edu_degree["+i+"]' name='edu_degree' value='"+edu_degree[i]+"'></td>";
                    profHTML = profHTML + "</tr><tr>";
                    profHTML =profHTML + "<td width='100px'>Activities</td><td> : <textarea id='edu_activities["+i+"]' name='edu_activities'>"+edu_activities[i]+"</textarea></td>";
                    profHTML = profHTML + "</tr><tr>";
                    profHTML =profHTML + "<td width='100px'>Notes</td><td> : <textarea id='edu_note["+i+"]' name='edu_note'>"+edu_notes[i]+"</textarea></td>";
                    profHTML = profHTML +"</tr><tr><td colspan='2'><hr width=200px align='left' style='margin-left:50px;'></td></tr>";
                }
                profHTML = profHTML + "<tr><td width='100px'>Skills</td><td> :<textarea id='skill' name='skill'>"+skill+"</textarea></td></tr>";
                profHTML = profHTML + "<tr>";
                profHTML = profHTML + "<td colspan='2'><hr width=600px align='left'></td>";
                profHTML = profHTML + "</tr><tr>";
                profHTML = profHTML + "<td colspan='2'><h2>ADDITIONAL INFORMATION</h2></td>";
                profHTML = profHTML + "</tr><tr>";
                profHTML =profHTML + "<td width='100px'>Date Of Birth</td><td> : <input type='text' id='dateOfBirth' name='dateOfBirth' value="+dateOfBirth+"></td>";
                profHTML = profHTML + "</tr><tr>";
                profHTML =profHTML + "<td width='100px'>Interest</td><td> : <input type='text' id='interest' name='interest' value='"+interest+"'></td>";
                profHTML = profHTML + "</tr><tr>";

                profHTML =profHTML + "</table>";
                profHTML = profHTML +"<input type='hidden' id='exp_title' name='exp_title' value='"+pos_title+"'>\n\
                    <input type='hidden' id='sess' name='sess' value='<?php echo $sess; ?>'>";                                                    
                profHTML = profHTML +"<input type='hidden' id='exp_com' name='exp_com' value='"+pos_company+"'>";
                profHTML = profHTML + "<input type='hidden' id='exp_date' name='exp_date' value='"+pos_date+"'>";
                profHTML = profHTML +"<input type='hidden' id='exp_summary' name='exp_summary' value='"+pos_summary+"'>";
                profHTML = profHTML +"<input type='hidden' id='edu_school' name='edu_school' value='"+edu_schoolName+"'>";
                profHTML = profHTML +"<input type='hidden' id='edu_field' name='edu_field' value='"+edu_fieldOfStudy+"'>";
                profHTML = profHTML +"<input type='hidden' id='edu_date' name='edu_date' value='"+edu_date+"'>";
                profHTML = profHTML + "<input type='hidden' id='edu_degree' name='edu_degree' value='"+edu_degree+"'>";
                profHTML = profHTML +"<input type='hidden' id='edu_act' name='edu_act' value='"+edu_activities+"'>";
                profHTML = profHTML +"<input type='hidden' id='edu_note' name='edu_note' value='"+edu_notes+"'>";
                profHTML =profHTML + "<td width='100px'><button class='btn' onclick='adddata()'>SUBMIT</button></td></tr>";
                profHTML = profHTML +"</form>";
                }
                if(document.getElementById("loginbadge")!= null){
                document.getElementById("loginbadge").innerHTML = profHTML;
                }
        }
        function adddata(){
            var xmlhttp;
                if (window.XMLHttpRequest)
                {// code for IE7+, Firefox, Chrome, Opera, Safari
                    xmlhttp=new XMLHttpRequest();
                }
                else
                {// code for IE6, IE5
                    xmlhttp=new ActiveXObject("Microsoft.XMLHTTP");
                }
                xmlhttp.onreadystatechange=function()
                {
                    if (xmlhttp.readyState==4 && xmlhttp.status==200)
                    {
                        document.getElementById('loginbadge').innerHTML=xmlhttp.responseText;
                    }
                }
                var sess = "<?php echo $sess; ?>";
                xmlhttp.open("GET","insert",true);
                xmlhttp.send();
                logout();
        }             
    </script>
    <script type="text/javascript">
        function add_exp(i){
            var data = "<form method='post' action="+'insertexp'+" id='form_exp'>";
            data = data + "<table bgcolor='#00FF00'>";
            data = data + "<tr>";
            data = data + "<td width='100px'>Position</td><td> :<input type='text' id='exp_pos' name='exp_pos'>\n\
                            <input type='hidden' name='sess' id='sess' value='<?php echo $sess; ?>'></td>";
            data = data + "</tr><tr>";
            data = data + "<td width='100px'>Company</td><td> :<input type='text' id='exp_com' name='exp_com'></td>";
            data = data + "</tr><tr>";
            data = data + "<td width='100px'>Date</td><td> :<input type='date' id='exp_date' name='exp_date'></td>";
            data = data + "</tr><tr>";
            data = data + "<td width='100px'>Summary</td><td> :<textarea id='exp_sum' name='exp_sum'></textarea></td>";
            data = data + "</tr><tr>";
            data = data + "<td width='100px' colspan='2'><input type='submit' value='Save' class='btn' style='margin-right:10px; height:30px;'><a href='/userdata?sess=<?php echo $sess;?>' class='btn'>Cancel</a></td>";
            data = data + "</tr>";    
            data = data + "</table>";
            data = data + "</form>";
            document.getElementById('exp'+i).innerHTML = data;
        }
        function cancel_exp(){
            return window.location='/index.php/job-seeker';
        }
       
        function add_edu(j){
            var data ="<form method='post' action="+'/insertedu'+">";
            data = data + "<table>";
            data = data + "<tr>";
            data = data + "<td width='100px'>School Name</td><td> :<input type='text' id='edu_schoolName' name='edu_schoolName'>\n\
                        <input type='hidden' name='sess' id='sess' value='<?php echo $sess; ?>'></td>";
            data = data + "</tr><tr>";
            data = data + "<td width='100px'>Field Of Study</td><td> :<input type='text' id='edu_fieldOfStudy' name='edu_fieldOfStudy'></td>";
            data = data + "</tr><tr>";
            data = data + "<td width='100px'>Date</td><td> :<input type='date' id='edu_date' name='edu_date'></td>";
            data = data + "</tr><tr>";
            data = data + "<td width='100px'>Degree</td><td> :<input type='text' id='edu_degree' name='edu_degree'></td>";
            data = data + "</tr><tr>";
            data = data + "<td width='100px'>Activities</td><td> :<textarea id='edu_act' name='edu_act'></textarea></td>";
            data = data + "</tr><tr>";
            data = data + "<td width='100px'>Notes</td><td> :<textarea id='edu_note' name='edu_note'></textarea></td>";
            data = data + "</tr><tr>";
            data = data + "<td width='100px' colspan='2'><input type='submit' value='Save' class='btn' style='margin-right:10px; height:30px;'><a href='/userdata?sess=<?php echo $sess;?>' class='btn'>Cancel</a></td>";
            data = data + "</tr>"
            data = data + "</table>";
            data = data + "</form>";
            document.getElementById('edu'+j).innerHTML = data;
        }
    </script>
    <script type="text/javascript">
        function show_edit_exp(exp_id,i){
            data_exp_pos = document.getElementById('data_exp_pos'+i).value;
            data_exp_com = document.getElementById('data_exp_com'+i).value;
            data_exp_date = document.getElementById('data_exp_date'+i).value;
            data_exp_sum = document.getElementById('data_exp_sum'+i).value;
              
            var data = "<div id='exp'"+i+"><form method='post' action="+'updateexp/'+exp_id+">";
            data = data + "<table bgcolor='#00FF00'>";
            data = data + "<tr>";
            data = data + "<td width='100px'>Position</td><td> :<input type='text' id='exp_pos' name='exp_pos' value='"+data_exp_pos+"'>\n\
                        <input type='hidden' name='sess' id='sess' value='<?php echo $sess; ?>'></td>";
            data = data + "</tr><tr>";
            data = data + "<td width='100px'>Company</td><td> :<input type='text' id='exp_com' name='exp_com' value='"+data_exp_com+"'></td>";
            data = data + "</tr><tr>";
            data = data + "<td width='100px'>Date</td><td> :<input type='date' id='exp_date' name='exp_date' value='"+data_exp_date+"'></td>";
            data = data + "</tr><tr>";
            data = data + "<td width='100px'>Summary</td><td> :<textarea id='exp_sum' name='exp_sum'>"+data_exp_sum+"</textarea></td>";
            data = data + "</tr><tr>";
            data = data + "<td width='100px' colspan='2'><input type='submit' value='Save' class='btn' style='margin-right:10px; height:30px;'><a href='/userdata?sess=<?php echo $sess;?>' class='btn'>Cancel</a></td>";
            data = data + "</tr>";    
            data = data + "</table>";
            data = data + "</form>";
            data = data + " <hr width='300px' style='margin-left: 80px;'></div>";
            document.getElementById('exp'+i).innerHTML = data;
        }
           
        function show_edit_edu(edu_id,j){
            data_edu_sn = document.getElementById('data_edu_sn'+j).value;
            data_edu_fs = document.getElementById('data_edu_fs'+j).value;
            data_edu_date = document.getElementById('data_edu_date'+j).value;
            data_edu_degree = document.getElementById('data_edu_degree'+j).value;
            data_edu_ac = document.getElementById('data_edu_ac'+j).value;
            data_edu_notes = document.getElementById('data_edu_notes'+j).value;

            var data = "<form method='post' action="+'updateedu/'+edu_id+">";
            data = data + "<table>";
            data = data + "<tr>";
            data = data + "<td width='100px'>School Name</td><td> :<input type='text' id='edu_schoolName' name='edu_schoolName' value='"+data_edu_sn+"'>\n\
                    <input type='hidden' name='sess' id='sess' value='<?php echo $sess; ?>'></td>";
            data = data + "</tr><tr>";
            data = data + "<td width='100px'>Field Of Study</td><td> :<input type='text' id='edu_fieldOfStudy' name='edu_fieldOfStudy' value='"+data_edu_fs+"'></td>";
            data = data + "</tr><tr>";
            data = data + "<td width='100px'>Date</td><td> :<input type='date' id='edu_date' name='edu_date' value='"+data_edu_date+"'></td>";
            data = data + "</tr><tr>";
            data = data + "<td width='100px'>Degree</td><td> :<input type='text' id='edu_degree' name='edu_degree' value='"+data_edu_degree+"'></td>";
            data = data + "</tr><tr>";
            data = data + "<td width='100px'>Activities</td><td> :<textarea id='edu_act' name='edu_act'>"+data_edu_ac+"</textarea></td>";
            data = data + "</tr><tr>";
            data = data + "<td width='100px'>Notes</td><td> :<textarea id='edu_note' name='edu_note'>"+data_edu_notes+"</textarea></td>";
            data = data + "</tr><tr>";
            data = data + "<td width='100px' colspan='2'><input type='submit' value='Save' class='btn' style='margin-right:10px; height:30px;'><a href='/userdata?sess=<?php echo $sess;?>' class='btn'>Cancel</a></td>";          
            data = data + "</tr>"
            data = data + "</table>";
            data = data + "</form>";
            document.getElementById('edu'+j).innerHTML = data;
        }
        function delete_exp(exp_id){
            var ask = confirm("Do you want to delete?");
            if(ask == true){
                var xmlhttp;
                if (window.XMLHttpRequest)
                {// code for IE7+, Firefox, Chrome, Opera, Safari
                    xmlhttp=new XMLHttpRequest();
                }
                else
                {// code for IE6, IE5
                    xmlhttp=new ActiveXObject("Microsoft.XMLHTTP");
                }
                xmlhttp.onreadystatechange=function()
                {
                    if (xmlhttp.readyState==4 && xmlhttp.status==200)
                    {
                        document.getElementById('bd').innerHTML=xmlhttp.responseText;
                    }
                }
                var sess = "<?php echo $sess; ?>";
                xmlhttp.open("GET","deleteexp/"+exp_id+"?sess="+sess,true);
                xmlhttp.send();
            }

        }
        function delete_edu(edu_id){
            var ask = confirm("Do you want to delete?");
            if(ask == true){
                var xmlhttp;
                if (window.XMLHttpRequest)
                {// code for IE7+, Firefox, Chrome, Opera, Safari
                    xmlhttp=new XMLHttpRequest();
                }
                else
                {// code for IE6, IE5
                    xmlhttp=new ActiveXObject("Microsoft.XMLHTTP");
                }
                xmlhttp.onreadystatechange=function()
                {
                    if (xmlhttp.readyState==4 && xmlhttp.status==200)
                    {
                        document.getElementById('bd').innerHTML=xmlhttp.responseText;
                    }
                }
                var sess = "<?php echo $sess; ?>";
                xmlhttp.open("GET","deleteedu/"+edu_id+"?sess="+sess,true);
                xmlhttp.send();
            }

        }
    </script>
</head>
<body>
    <div id="bd">
    <div id="loginbadge" style="margin-left: 50px;">
        <form method="post" action="insertsub" enctype='multipart/form-data'>
        <?php if (count($cv) == null) { ?>
        <table>
            <tr>
                <td colspan="2"><img src="http://static02.linkedin.com/scds/common/u/img/icon/icon_no_photo_80x80.png">
                    <input type="hidden" id="sess" name="sess" value="<?php echo $sess; ?>">
                </td>
            </tr>
            <tr>
                <td width="100px">Upload Profile</td> <td>: <input type="file" id="pic_url" name="pic_url"></td>
            </tr>
            <input type="hidden" id="id" name="id"><br>
            <tr>
                <td width="100px">First Name</td> <td>: <input type="text" id="first_name" name="first_name"></td>
            </tr>
            <tr>
                <td width="100px">Last Name</td> <td>: <input type="text" id="last_name" name="last_name"></td>
            </tr>
            <tr>
                <td>Job Category</td>
                <td>: 

                    <select id="jobs_cate" name="jobs_cate">
                    <?php foreach ($result as $r): ?>
                         <option value="<?php echo $r->cat_id; ?>"><?php echo $r->cat_name; ?></option>
                    <?php endforeach;?>
                    </select>
                </td>
            </tr>
        </table>

        <div id="addexp">
            <hr width="600px">
            <h2>EXPERIENCES</h2>
            <?php
            $i = 0;
            foreach ($datas as $k):
            ?>
                <div id='<?php echo "exp" . $i; ?>' >
                    <table><a href="#"><img src="./images/delete.png" onclick="delete_exp('<?php echo $k['exp_id']; ?>')" align="right" style="padding-right:300px;"></a>
                        <a href="#"><img src="./images/edit1.png" onclick="show_edit_exp('<?php echo $k['exp_id']; ?>','<?php echo $i; ?>')" align="right" style="padding-right: 10px;"></a>

                        <tr>
                            <td width="100px">Position</td> <td id="data_exp_pos">: <?php echo $k['exp_position']; ?>
                                <input type="hidden" id='<?php echo "data_exp_pos" . $i; ?>' value="<?php echo $k['exp_position']; ?>">
                            </td>
                        </tr>
                        <tr>
                            <td width="100px">Company</td> <td>: <?php echo $k['exp_company']; ?>
                                <input type="hidden" id='<?php echo "data_exp_com" . $i; ?>' value="<?php echo $k['exp_company']; ?>">
                            </td>
                        </tr>
                        <tr>
                            <td width="100px">Date</td> <td>: <?php echo $k['exp_date']; ?>
                                <input type="hidden" id='<?php echo "data_exp_date" . $i; ?>' value="<?php echo $k['exp_date']; ?>">
                            </td>
                        </tr>
                        <tr>
                            <td width="100px">Summary</td> <td>: <?php echo $k['exp_summary']; ?>
                                <input type="hidden" id='<?php echo "data_exp_sum" . $i; ?>' value="<?php echo $k['exp_summary']; ?>">
                            </td>
                        </tr>
                    </table>
                    <hr width="300px" style="margin-left: 80px;">
                </div>

            <?php
            $i++;
            endforeach;
            ?>
            <div id='<?php echo "exp" . $i; ?>'>
                <button onclick="add_exp('<?php echo $i; ?>');" class="btn btn-link">Add Experiences</button>
            </div>
        </div>

        <div id="addedu">
            <hr width="600px">
            <h2>EDUCATION</h2>
            <?php
            $j = 0;
            foreach ($result_edu as $re):
            ?>
                <div id='<?php echo "edu" . $j; ?>'>
                    <table><a href="#"><img src="./images/delete.png" onclick="delete_edu('<?php echo $re['edu_id']; ?>')" align="right" style="padding-right:300px;"></a>
                        <a href="#"><img src="./images/edit1.png" onclick="show_edit_edu('<?php echo $re['edu_id']; ?>','<?php echo $j; ?>')" align="right" style="padding-right: 10px;"></a
                        <tr>
                            <td width="100px">School Name</td> <td>: <?php echo $re['edu_schoolName']; ?>
                                <input type="hidden" id='<?php echo "data_edu_sn" . $j; ?>' value="<?php echo $re['edu_schoolName']; ?>">
                            </td>
                        </tr>
                        <tr>
                            <td width="100px">Field Of Study</td> <td>: <?php echo $re['edu_field']; ?>
                                <input type="hidden" id='<?php echo "data_edu_fs" . $j; ?>' value="<?php echo $re['edu_field']; ?>">
                            </td>
                        </tr>
                        <tr>
                            <td width="100px">Date</td> <td>: <?php echo $re['edu_date']; ?>
                                <input type="hidden" id='<?php echo "data_edu_date" . $j; ?>' value="<?php echo $re['edu_date']; ?>">
                            </td>
                        </tr>
                        <tr>
                            <td width="100px">Degree</td> <td>: <?php echo $re['edu_degree']; ?>
                                <input type="hidden" id='<?php echo "data_edu_degree" . $j; ?>' value="<?php echo $re['edu_degree']; ?>">
                            </td>
                        </tr>
                        <tr>
                            <td width="100px">Activities</td> <td>: <?php echo $re['edu_activities']; ?>
                                <input type="hidden" id='<?php echo "data_edu_ac" . $j; ?>' value="<?php echo $re['edu_activities']; ?>">
                            </td>
                        </tr>
                        <tr>
                            <td width="100px">Notes</td> <td>: <?php echo $re['edu_notes']; ?>
                                <input type="hidden" id='<?php echo "data_edu_notes" . $j; ?>' value="<?php echo $re['edu_notes']; ?>">
                            </td>
                        </tr>
                    </table>
                </div>
                <hr width="300px" style="margin-left: 80px;">
            <?php
            $j++;
            endforeach;
            ?>
            <div id='<?php echo "edu" . $j; ?>'>
                <button onclick="add_edu(<?php echo $j; ?>)" class="btn btn-link">Add Education</button>
            </div>
        </div>

        <table>
            <tr>
                <td colspan="2"><hr width="600px"></td>
            </tr>
            <tr>
                <td colspan="2"><h2>ADDITIONAL INFORMATION</h2></td>
            </tr>
            <tr>
                <td width="100px">Interest</td> <td>: <textarea width="400px" height="200px" id="interest" name="interest"></textarea></td>
            </tr>
            <tr>
                <td width="100px">Date Of Birth</td> <td>: <input type="date" id="dateOfBirth" name="dateOfBirth" class="datepicker" data-date-format="yyyy-mm-dd"></td>
            </tr>
            <tr>
                <td width="100px"><input type="submit" value="SUBMIT" class='btn'></td>
            </tr>
        </table>
    <?php
    }else {
        foreach ($cv as $cv_element):
    ?>
        <table>
            <tr>
                <td colspan="2"><img src="<?php echo $cv_element['pic_url'];?>" style="width:80px; height: 80px;">
                    <input type="hidden" id="sess" name="sess" value="<?php echo $sess; ?>">
                </td>
            </tr>
            <tr>
                <td width="100px">Upload Profile</td> <td>: <input type="file" id="pic_url" name="pic_url"></td>
            </tr>
            <input type="hidden" id="id" name="id"><br>
            <tr>
                <td width="100px">First Name</td> <td>: <input type="text" id="first_name" name="first_name" value="<?php echo $cv_element['first_name']; ?>"></td>
            </tr>
            <tr>
                <td width="100px">Last Name</td> <td>: <input type="text" id="last_name" name="last_name" value="<?php echo $cv_element['last_name']; ?>"></td>
            </tr>
            <tr>
                <td>Job Category</td>
                <td>: 

                    <select id="jobs_cate" name="jobs_cate">
                        <?php foreach ($cat_name as $cat_name_): ?>
                            <option selected="selected" value="<?php echo $cv_element['jobs_cate']; ?>"><?php echo $cat_name_['cat_name']; ?></option>
                            <?php
                        endforeach;
                        foreach ($result as $r):
                            ?>
                            <option value="<?php echo $r->cat_id; ?>"><?php echo $r->cat_name; ?></option>
                            <?php
                        endforeach;
                        ?>
                    </select>
                </td>
            </tr>
        </table>

        <div id="addexp">
            <hr width="600px">
            <h2>EXPERIENCES</h2>
            <?php
            $i = 0;
            foreach ($datas as $k):
            ?>
                <div id='<?php echo "exp" . $i; ?>' >
                    <table><a href="#"><img src="./images/delete.png" onclick="delete_exp('<?php echo $k['exp_id']; ?>')" align="right" style="padding-right:300px;"></a>
                        <a href="#"><img src="./images/edit1.png" onclick="show_edit_exp('<?php echo $k['exp_id']; ?>','<?php echo $i; ?>')" align="right" style="padding-right: 10px;"></a>

                        <tr>
                            <td width="100px">Position</td> <td id="data_exp_pos">: <?php echo $k['exp_position']; ?>
                                <input type="hidden" id='<?php echo "data_exp_pos" . $i; ?>' value="<?php echo $k['exp_position']; ?>">
                            </td>
                        </tr>
                        <tr>
                            <td width="100px">Company</td> <td>: <?php echo $k['exp_company']; ?>
                                <input type="hidden" id='<?php echo "data_exp_com" . $i; ?>' value="<?php echo $k['exp_company']; ?>">
                            </td>
                        </tr>
                        <tr>
                            <td width="100px">Date</td> <td>: <?php echo $k['exp_date']; ?>
                                <input type="hidden" id='<?php echo "data_exp_date" . $i; ?>' value="<?php echo $k['exp_date']; ?>">
                            </td>
                        </tr>
                        <tr>
                            <td width="100px">Summary</td> <td>: <?php echo $k['exp_summary']; ?>
                                <input type="hidden" id='<?php echo "data_exp_sum" . $i; ?>' value="<?php echo $k['exp_summary']; ?>">
                            </td>
                        </tr>
                    </table>
                    <hr width="300px" style="margin-left: 80px;">
                </div>

                <?php
                    $i++;
                endforeach;
                ?>
                <div id='<?php echo "exp" . $i; ?>'>
                    <button onclick="add_exp('<?php echo $i; ?>');" class="btn btn-link">Add Experiences</button>
                </div>
            </div>

            <div id="addedu">
                <hr width="600px">
                <h2>EDUCATION</h2>
                <?php
                $j = 0;
                foreach ($result_edu as $re):
                ?>
                    <div id='<?php echo "edu" . $j; ?>'>
                        <table><a href="#"><img src="./images/delete.png" onclick="delete_edu('<?php echo $re['edu_id']; ?>')" align="right" style="padding-right:300px;"></a>
                            <a href="#"><img src="./images/edit1.png" onclick="show_edit_edu('<?php echo $re['edu_id']; ?>','<?php echo $j; ?>')" align="right" style="padding-right: 10px;"></a
                            <tr>
                                <td width="100px">School Name</td> <td>: <?php echo $re['edu_schoolName']; ?>
                                    <input type="hidden" id='<?php echo "data_edu_sn" . $j; ?>' value="<?php echo $re['edu_schoolName']; ?>">
                                </td>
                            </tr>
                            <tr>
                                <td width="100px">Field Of Study</td> <td>: <?php echo $re['edu_field']; ?>
                                    <input type="hidden" id='<?php echo "data_edu_fs" . $j; ?>' value="<?php echo $re['edu_field']; ?>">
                                </td>
                            </tr>
                            <tr>
                                <td width="100px">Date</td> <td>: <?php echo $re['edu_date']; ?>
                                    <input type="hidden" id='<?php echo "data_edu_date" . $j; ?>' value="<?php echo $re['edu_date']; ?>">
                                </td>
                            </tr>
                            <tr>
                                <td width="100px">Degree</td> <td>: <?php echo $re['edu_degree']; ?>
                                    <input type="hidden" id='<?php echo "data_edu_degree" . $j; ?>' value="<?php echo $re['edu_degree']; ?>">
                                </td>
                            </tr>
                            <tr>
                                <td width="100px">Activities</td> <td>: <?php echo $re['edu_activities']; ?>
                                    <input type="hidden" id='<?php echo "data_edu_ac" . $j; ?>' value="<?php echo $re['edu_activities']; ?>">
                                </td>
                            </tr>
                            <tr>
                                <td width="100px">Notes</td> <td>: <?php echo $re['edu_notes']; ?>
                                    <input type="hidden" id='<?php echo "data_edu_notes" . $j; ?>' value="<?php echo $re['edu_notes']; ?>">
                                </td>
                            </tr>
                        </table>
                    </div>
                    <hr width="300px" style="margin-left: 80px;">
                <?php
                $j++;
                endforeach;
                ?>
                <div id='<?php echo "edu" . $j; ?>'>
                    <button onclick="add_edu(<?php echo $j; ?>)" class="btn btn-link">Add Education</button>
                </div>
            </div>

            <table>
                <tr>
                    <td colspan="2"><hr width="600px"></td>
                </tr>
                <tr>
                    <td colspan="2"><h2>ADDITIONAL INFORMATION</h2></td>
                </tr>
                <tr>
                    <td width="100px">Interest</td> <td>: <textarea width="400px" height="200px" id="interest" name="interest"><?php echo $cv_element['interest']; ?></textarea></td>
                </tr>
                <tr>
                    <td width="100px">Date Of Birth</td> <td>: <input type="text" id="datepicker" name="dateOfBirth" class="datepicker" data-date-format="yyyy-mm-dd" placeholder="<?php echo $cv_element['date_of_birth'];?>"></td>
                </tr>
                <tr>
                    <td width="100px"><input type="submit" value="SUBMIT" class='btn'></td>
                </tr>
            </table>     
        <?php
    endforeach;
    }
    ?>
    </form>
 </div>
    </div>
    <div style ="margin-left: 50px; margin-top: 30px;"><script type="IN/Login"></script></div>
    <script type="text/javaScript">
    $(function() {
     $(".datepicker").datepicker();
   });
</script>