
<!DOCTYPE html>
<html lang="en"><head>
<meta http-equiv="content-type" content="text/html; charset=UTF-8">
<!--basic styles-->
<link href="/dashboard/a_data/bootstrap.css" rel="stylesheet">
<link href="/dashboard/a_data/bootstrap-responsive.css" rel="stylesheet">
<link rel="stylesheet" href="/dashboard/a_data/font-awesome.css">
<body>	
    
   <style type="text/css">
div.styled {
  border-width:6px;
  border-color:#ff9900;
  border-style: double;
  }
   </style>
    
    <div style="width: 500px; height: auto; padding: 30px; margin: 20px; " class="styled">
    <div class="widget-box">
        <div class="widget-body">
	<div class="widget-main">
            <div style="width: 90%; min-height: 150px; padding: 0px; position: relative;" id="piechart-placeholder"></div>
	</div><!--/widget-main-->
        </div><!--/widget-body-->
    </div><!--/widget-box-->  
   </div> 
<script src="/dashboard/a_data/jquery_007.js"></script>
<script type="text/javascript">
	window.jQuery || document.write("<script src='themes/js/jquery-1.9.1.min.js'>"+"<"+"/script>");
</script>
<script src="/dashboard/a_data/bootstrap.js"></script>
<script src="/dashboard/a_data/jquery-ui-1.js"></script>
<script src="/dashboard/a_data/jquery_006.js"></script>
<script src="/dashboard/a_data/jquery_002.js"></script>
<script src="/dashboard/a_data/jquery_003.js"></script>
<script src="/dashboard/a_data/jquery.js"></script>
<script src="/dashboard/a_data/jquery_004.js"></script>
<script src="/dashboard/a_data/jquery_005.js"></script>
<!--w8 scripts-->
<script src="/dashboard/a_data/w8-elements.js"></script>
<script src="/dashboard/a_data/w8.js"></script>
<?php 
$i =0;
$job_seeker =0;
$company =0;
$ca =0;
foreach ($dashboard as $das){
  $sta = $das->statues;
  if($sta ==0){
      $job_seeker++;
  }
  if($sta==1){
      $company++;
  }
  if($sta == 2){
      $ca++;
  }
  $i++;   
}
?>

<!--inline scripts related to this page-->
		<script type="text/javascript">
			$(function() {
			  var data = [
				{ label: "Administrator",  data: <?php echo $ca; ?>, color: "#AF4E96"},
				{ label: "Company",  data: <?php echo $company ;?>, color: "#2091CF"},
				{ label: "Job seeker",  data: <?php echo $job_seeker ;?>, color: "#68BC31"},	
			  ];
			
			  var placeholder = $('#piechart-placeholder').css({'width':'90%' , 'min-height':'150px'});
			  $.plot(placeholder, data, {
				
				series: {
			        pie: {
			            show: true,
						tilt:0.8,
						highlight: {
							opacity: 0.25
						},
						stroke: {
							color: '#fff',
							width: 2
						},
						startAngle: 2
			        }
			    },
			    legend: {
			        show: true,
					position: "ne", 
				    labelBoxBorderColor: null,
					margin:[-30,15]
			    }
				,
				grid: {
					hoverable: true,
					clickable: true
				},
				tooltip: true, //activate tooltip
				tooltipOpts: {
					content: "%s : %y.1",
					shifts: {
						x: -30,
						y: -50
					}
				}
			 });
			
			  var $tooltip = $("<div class='tooltip top in' style='display:none;'><div class='tooltip-inner'></div></div>").appendTo('body');
			  placeholder.data('tooltip', $tooltip);
			  var previousPoint = null;
			
			  placeholder.on('plothover', function (event, pos, item) {
				if(item) {
					if (previousPoint != item.seriesIndex) {
						previousPoint = item.seriesIndex;
						var tip = item.series['label'] + " : " + item.series['percent']+'%';
						$(this).data('tooltip').show().children(0).text(tip);
					}
					$(this).data('tooltip').css({top:pos.pageY + 10, left:pos.pageX + 10});
				} else {
					$(this).data('tooltip').hide();
					previousPoint = null;
				}
				
			 });
			
				var d1 = [];
				for (var i = 0; i < Math.PI * 2; i += 0.5) {
					d1.push([i, Math.sin(i)]);
				}
			
				var d2 = [];
				for (var i = 0; i < Math.PI * 2; i += 0.5) {
					d2.push([i, Math.cos(i)]);
				}
			
				var d3 = [];
				for (var i = 0; i < Math.PI * 2; i += 0.2) {
					d3.push([i, Math.tan(i)]);
				}
				
				var sales_charts = $('#sales-charts').css({'width':'100%' , 'height':'220px'});
				$.plot("#sales-charts", [
					{ label: "Domains", data: d1 },
					{ label: "Hosting", data: d2 },
					{ label: "Services", data: d3 }
				], {
					hoverable: true,
					shadowSize: 0,
					series: {
						lines: { show: true },
						points: { show: true }
					},
					xaxis: {
						tickLength: 0
					},
					yaxis: {
						ticks: 10,
						min: -2,
						max: 2,
						tickDecimals: 3
					},
					grid: {
						backgroundColor: { colors: [ "#fff", "#fff" ] },
						borderWidth: 1,
						borderColor:'#555'
					}
				});			
			})
		</script>		
</body>
</html>