

<?php if($jjs != null){ ?>
<table border="1">
    <tr>
        <th>job title</th>
        <th> user apply </th>
    </tr>
<?php 
    foreach ($jjs as $jobs){
        
        $jcat = $jobs['jcat_id'];
        echo '<tr>';  
          echo '<td>'.$jobs['title'].'</td>';        
          echo '<td>';
            foreach ($jobs['us'] as $n){ 
                
               $jca = $n->jcat_id;
               
               if($jca == $jcat){
                    echo  '<span class="label label-success"> '.$n->username.'</span> : <a href=" '. $this->url('jobs/pdf', array('controller'=> 'Job', 'action' => 'pdf', 'id' =>$n->id)) . ' " > [<img src ="./images/pdf.png">]</a> <br /> ';
               }
            }  
            echo '</td>';
       echo '</tr>';
    }
?>
</table>
<?php 
 }  else {
    echo 'it have no user apply';  
 }
?>
   







 

