<script type="text/javascript" src="/tinyeditor/nicEdit.js"></script>

<script type="text/javascript">
                //<![CDATA[
                bkLib.onDomLoaded(function() { nicEditors.allTextAreas() });
                 //]]>
</script>

<script type="text/javaScript">
    $(function() {
     $(".datepicker").datepicker();
   });
</script>
<style>          
    h2 {
	display: inline;
	position: relative;
	font: 40px Helvetica, Sans-Serif;
	letter-spacing: -5px;
	color: rgba(0,0,255,0.5); 
}
    h2:after {
	position: absolute; left: 10px; top: 5px;
	color: rgba(255,0,0,0.5);   
}
</style>
<div style = "text-align: center"><h2>Edit your job </h2></div><br />

<form class="form-horizontal" method="post" method="post" action="<?php echo $this->url('home/action', array('action' => 'update')) ?>">   
    <fieldset>
        <div class="control-group">
            <label class="control-label" for="#"></label>
            <div class="controls">
                <input type="hidden" name="session" value="<?php echo $session ?>" />
            </div>
        </div>
        
        <div class="control-group">
            <label class="control-label" for="#"></label>
            <div class="controls">
                <input type="hidden" name="job_id" value="<?php echo $job->getJobId(); ?>" />
            </div>
        </div>
           
       <div class="control-group">
            <label class="control-label" for="#">Title</label>
            <div class="controls">
                <input type="text" name ="job_title" value="<?php echo $job->getJobTitle()?> ">
            </div>
       </div>
            
       <div class="control-group">
            <label class="control-label" for="#">Close date</label>
            <div class="controls">
                <input type="text" name="job_deadline"class="datepicker" value=" <?php echo $job->getJobDeadline() ?> ">
            </div>
       </div>
            
         <div class="control-group">
            <label class="control-label" for="inputEmail">Address </label>
            <div class="controls">
                <input type="text" name ="job_location" value="<?php echo $job->getJobLocation(); ?>">
          </div>
        </div>
            
         <div class="control-group">
            <label class="control-label" for="inputEmail">Salary</label>
            <div class="controls">
                <input type="text" name ="job_salary" value="<?php echo $job->getJobSalary(); ?>">
          </div>
          </div>
            
         <div class="control-group">
            <label class="control-label" for="inputEmail">Benefit </label>
            <div class="controls">
                <textarea rows="3" name="job_benefit" style="width: 70%;"><?php echo $job->getJobBenefit(); ?></textarea>
            </div>
        </div>
            
         <div class="control-group">
            <label class="control-label" for="#">About company</label>
            <div class="controls">
                <textarea rows="3" name="about_company" style="width: 70%;"><?php echo $job->getAboutCompany(); ?></textarea>
          </div>
         </div>
            
         <div class="control-group">
            <label class="control-label" for="#">Description</label>
            <div class="controls">
                <textarea rows="2" name="job_description" style="width: 70%;"><?php echo $job->getJobDescription(); ?></textarea>
            </div>
        </div>
            
        <div class="control-group">
            <label class="control-label" for="inputEmail">How apply </label>
            <div class="controls">
                <textarea rows="1" name="job_apply" style="width: 70%;"><?php echo $job->getJobApply(); ?></textarea>
          </div>
        </div>
            
         <div class="control-group">
            <label class="control-label" for="inputEmail"></label>
            <div class="controls">
                <button type="submit" class="btn"><?php echo $submitText ?></button>
          </div>
        </div>
    </fieldset>
</form>
