<script type="text/javascript" src="/tinyeditor/nicEdit.js"></script>
<script type="text/javascript">
                //<![CDATA[
                bkLib.onDomLoaded(function() { nicEditors.allTextAreas() });
                 //]]>
</script>
<script type="text/javaScript">
    $(function() {
     $(".datepicker").datepicker();
   });
</script>
<?php 

 $sess = isset($_GET['sess']) ? $_GET['sess'] : "";

foreach ($com as $d){

    
}
$com_id = $d->com_id;
?>

<form class="form-horizontal" method="post" action="<?php echo $this->url('home/action', array('action' => 'new-job')) ?>">
    <fieldset>
        <div class="control-group">
            <label class="control-label"></label>
            <div class="controls">
                <input type="hidden" name ="session"  value="<?php echo $sess;  ?>">     
            </div>
        </div>
        
        <div class="control-group">
            <label class="control-label" for="inputEmail"></label>
            <div class="controls">
                <input type="hidden" name ="com_id" placeholder="company id…" value="<?php echo $com_id;  ?>">     
            </div>
        </div>
            
         <div class="control-group">
            <label class="control-label" for="inputEmail">Title</label>
            <div class="controls">   
                <input type="text" name ="job_title" placeholder="job title…">
            </div>
        </div>
            
        <div class="control-group">
            <label class="control-label" for="inputEmail">Category</label>
            <div class="controls">
                <select name="cat_id">
		 <?php foreach($categories as $c) {
                            echo '<option value=' . $c->getCatId() . '>' . $c->getCatName(). '</option>';
                    }
		 ?>
                </select>
            </div>
        </div>
            
        <div class="control-group">
            <label class="control-label" for="inputEmail">Address</label>
            <div class="controls">
                <input type="text" name ="job_location" placeholder="job location…">
            </div>
        </div>
            
        <div class="control-group">
            <label class="control-label" for="inputEmail">Salary</label>
            <div class="controls">
                <input type="text" name ="job_salary" placeholder="salary…">
            </div>
        </div>
            
        <div class="control-group">
            <label class="control-label" for="inputEmail">Close date</label>
            <div class="controls">
                <input type="text" name="job_deadline" class="datepicker" placeholder="job deadline" data-date-format="yyyy-mm-dd">
            </div>
        </div>
            
        <div class="control-group">
            <label class="control-label" for="inputEmail">Benefit</label>
            <div class="controls">
                <input type="text" name ="job_benefit" placeholder="benefit…">
            </div>
        </div>
            
        <div class="control-group">
            <label class="control-label" for="inputEmail">About company</label>
            <div class="controls">
                 <textarea rows="3" name="about_company" style="width: 70%;"></textarea>
            </div>
         </div>
            
        <div class="control-group">
            <label class="control-label" for="inputEmail">Description</label>
            <div class="controls">
                <textarea rows="3" name="job_description" style="width: 70%;"></textarea>
            </div>
        </div>
            
        <div class="control-group">
            <label class="control-label" for="inputEmail">How apply</label>
            <div class="controls">
                <textarea rows="3" name="job_apply" style="width: 70%;"></textarea>
            </div>
        </div>
            
        <div class="control-group">
            <label class="control-label" for="inputEmail"></label>
            <div class="controls">
                <button type="submit" class="btn">Submit</button>
            </div>
        </div>
       
    </fieldset>
</form>
	



	


