<?php 
// module/Job/view/Job/Subject/add.phtml

//This for alert succussful 
if($message!= NULL){
echo $message;
}

//Lits subjects or skills
$ids = $id;
echo '<table class="table table-striped table-hover">';
foreach ($subjects as $su){ 
    $cat_id = $this->escapeHtml($su->cat_id);
    ?>
    <tr>
    <td><?php echo $this->escapeHtml($su->sub_id);?></td>
    <td><?php echo $this->escapeHtml($su->sub_name);?></td>
    </tr>
    <?php
}
echo '</table>';
// form add new skill
$title = 'Add new subject';
$this->headTitle($title);
?>
<?php
$form = $this->form;
$form->setAttribute('action', $this->url('home/action', array('action' => 'new-subject')));
$form->prepare();

echo '<div class="label">';
echo '<h2 class ="ui-widget-header">';
    echo $this->escapeHtml($title);
echo '</h2>';
echo $this->form()->openTag($form);

 echo '<div class="control-group">';
    echo '<label class="control-label"></label>';
        echo '<div class="controls">';  ?>
            <input type ="hidden" name ="cat_id" value =" <?php  echo $ids ?> ">
 <?php echo '</div>';
    echo '</div>';    
    echo '<div class="control-group">';
    echo '<label class="control-label">Subject:</label>';
        echo '<div class="controls">';
            echo $this->formRow($form->get('sub_name'));
        echo '</div>';
    echo '</div>';  
echo $this->formSubmit($form->get('submit'));
echo $this->form()->closeTag();
echo '</div>';
?>
