<style>  
    h2 {
	display: inline;
	position: relative;
	font: 40px Helvetica, Sans-Serif;
	letter-spacing: -5px;
	color: rgba(0,0,255,0.5); 
}
    h2:after {
   
	position: absolute; left: 10px; top: 5px;
	color: rgba(255,0,0,0.5);   
}
</style>
<div style="margin-left:50px;"><h2>List categories</h2></div><br /><br />


<table  class="table table-striped table-hover">
    <tr>
        <th>Id</th>
        <th>Name</th>
    <tr>
    
<?php 

foreach ($categories as  $cat){
    echo '<tr>';
    echo '<td>'.$cat->getcatId().'</td>';
    echo '<td>'.$cat->getcatName().'</td>';
    echo '<td>';
         echo '<a href=" '. $this->url('home/action',array(
            'action'=>'new-subject', 'id' => $cat->getcatId())). ' ">Add</a>';
    echo '</td>';
    echo '</tr>';
}
?>

</table><br />

    
<form class="form-horizontal" method="post" action="<?php echo $this->url('home/action', array('action' => 'createCategory')) ?>">
    <fieldset>      
        <div class="control-group">
            <label class="control-label"></label>
            <div class="controls">  
                 <h4>Add new category</h4>
            </div>
        </div>
         <div class="control-group">
            <label class="control-label" for="inputEmail">Category</label>
            <div class="controls">  
                <input type="text" name ="cat_name" placeholder="category name…"> <br />
            </div>
        </div>
            
        <div class="control-group">
            <label class="control-label" for="inputEmail"></label>
            <div class="controls">  
                <button type="submit" class="btn">Submit</button>
            </div>
        </div>
    </fieldset>
</form>
