<?php




?>



<form class="form-horizontal" method="post" action="<?php echo $this->url('home/action', array('action' => 'percentageForm')) ?>">
    <fieldset>
       <?php
       $i=0;
       foreach ($per as $pers){ 
           $i++;
    //var_dump($pers);
           
           ?>
            <input type="hidden" name ="form[]"  value="1" />  
           <input type="hidden" name ="jcat_id[]"  value=" <?php echo $pers->sub_id ?> ">     
           <input type="hidden" name ="sub_id[]"  value=" <?php echo '12' ?> ">     
         <div class="control-group">
            <label class="control-label" for="inputEmail"> <?php echo $pers->sub_name ?></label>
            <div class="controls">
                <input type="text" name ="percentage[]" placeholder="value…">
            </div>
        </div>
       <?php } ?>
        <div class="control-group">
            <label class="control-label" for="inputEmail"></label>
            <div class="controls">
                <button type="submit" class="btn btn-success">Submit</button>
            </div>
        </div>
    </fieldset>
</form>

<div class="alert alert-block alert-error">
     <a class="close" data-dismiss="alert" href="#">X</a>
     <h4 class="alert-heading">Error!</h4>
       Please try again...
</div>
<div class="alert alert-block alert-success">
     <a class="close" data-dismiss="alert" href="#">X</a>
     <h4 class="alert-heading">Success!</h4>
     You hade successfully submitted.
</div>
<div class="alert alert-block alert-info">
     <a class="close" data-dismiss="alert" href="#">X</a>
     <h4 class="alert-heading">Info</h4>
     This is some informational text...
</div>